"""
Unit tests for CSRF token generation and validation in archer.auth.csrf.

Tests the actual behaviour of validate_csrf_token():
  - A freshly generated token validates successfully (returns True).
  - A tampered token fails validation (returns False).
  - An empty string token fails validation (returns False).
  - A token signed with a different secret fails validation (returns False).

Safe stub secrets are supplied by backend/tests/conftest.py via
os.environ.setdefault() before any test module is imported.
validate_csrf_token() catches SignatureExpired and BadSignature internally and
returns False; it never raises to the caller.
"""

import pytest

from archer.auth.csrf import generate_csrf_token, validate_csrf_token


@pytest.mark.unit
def test_valid_token_is_accepted() -> None:
    """A token generated by generate_csrf_token() passes validation."""
    token = generate_csrf_token()
    assert validate_csrf_token(token) is True


@pytest.mark.unit
def test_tampered_token_is_rejected() -> None:
    """A token with its signature segment replaced fails validation."""
    token = generate_csrf_token()
    # URLSafeTimedSerializer tokens are dot-separated: payload.timestamp.signature
    # Replace the signature segment entirely with a known-invalid string so that
    # itsdangerous reliably raises BadSignature regardless of token content.
    parts = token.split(".")
    parts[-1] = "invalidsignatureXXXXXXXXXXXX"
    tampered = ".".join(parts)
    assert validate_csrf_token(tampered) is False


@pytest.mark.unit
def test_empty_string_token_is_rejected() -> None:
    """An empty string is not a valid CSRF token."""
    assert validate_csrf_token("") is False


@pytest.mark.unit
def test_arbitrary_string_token_is_rejected() -> None:
    """An arbitrary string that was never signed is not a valid CSRF token."""
    assert validate_csrf_token("not-a-real-token") is False


@pytest.mark.unit
def test_token_from_different_secret_is_rejected() -> None:
    """A token signed with a different secret fails validation."""
    from itsdangerous import URLSafeTimedSerializer

    other_serializer = URLSafeTimedSerializer("completely-different-secret")
    foreign_token = other_serializer.dumps("csrf_token", salt="csrf-protection")
    # This token was signed correctly but with a different key; must be rejected.
    assert validate_csrf_token(foreign_token) is False